[package]
name = "npng_core"
version = "0.0.0-experimental"
description = "Types and traits for npng_crate"
authors = ["snowflakes14"]
edition = "2024"

[dependencies]
bincode = "2.0.1"
bytes = "1.10.1"
flate2 = "1.1.5"
zstd = "0.13.3"
thiserror = "2.0.17"

[lib]
doctest = false
test = false